# JuliaFormatter.jl configuration
# See https://domluna.github.io/JuliaFormatter.jl/stable/config/ for all options

# General formatting options
margin = 92
indent = 4
always_for_in = true
whitespace_typedefs = true
whitespace_ops_in_indices = true

# Trailing commas
trailing_comma = true

# Align struct fields
align_struct_field = true

# Function definition style
short_to_long_function_def = false
long_to_short_function_def = false

# Import/using formatting
align_assignment = true
normalize_line_endings = "unix"

# Documentation formatting
format_docstrings = true
align_matrix = true

# Conditional formatting
always_use_return = false
remove_extra_newlines = true

# Pipe formatting
pipe_to_function_call = true
